export const DECKS_SET_LOADING = 'DECKS_SET_LOADING';
export const DECKS_SET_DATA = 'DECKS_SET_DATA';
export const DECKS_ADD_DATA = 'DECKS_ADD_DATA';
export const DECKS_REMOVE_DATA = 'DECKS_REMOVE_DATA';
export const DECKS_UPDATE_FILTER = 'DECKS_UPDATE_FILTER';

export const DECK_SET_TESTING = 'DECK_SET_TESTING';
export const DECK_EMPTY_RESULTS = 'DECK_EMPTY_RESULTS';
export const DECK_QUIZ_RESET = 'DECK_QUIZ_RESET';
export const DECK_QUIZ_SET_ACTIVE_SLIDE = 'DECK_QUIZ_SET_ACTIVE_SLIDE';
export const DECK_QUIZ_SET_QUESTION_CORRECT = 'DECK_QUIZ_SET_QUESTION_CORRECT';
export const DECK_QUIZ_SET_FINISHED = 'DECK_QUIZ_SET_FINISHED';
export const DECK_SET_QUIZ_DEFAULT_SWIPE_CORRECT = 'DECK_SET_QUIZ_DEFAULT_SWIPE_CORRECT';
export const DECK_SET_CAROUSEL_INITIALIZED = 'DECK_SET_CAROUSEL_INITIALIZED';
