export const DECKS_SET_LOADING = 'DECKS_SET_LOADING';
export const DECKS_SET_DATA = 'DECKS_SET_DATA';
export const DECKS_ADD_DATA = 'DECKS_ADD_DATA';
export const DECKS_REMOVE_DATA = 'DECKS_REMOVE_DATA';
export const DECKS_UPDATE_FILTER = 'DECKS_UPDATE_FILTER';

export const DECK_SET_TESTING = 'DECK_SET_TESTING';
export const DECK_QUIZ_SET_ACTIVE_SLIDE = 'DECK_QUIZ_SET_ACTIVE_SLIDE';
