export const DECKS_SET_LOADING = 'DECKS_SET_LOADING';
export const DECKS_SET_DATA = 'DECKS_SET_DATA';
export const DECKS_ADD_DATA = 'DECKS_ADD_DATA';
export const DECKS_REMOVE_DATA = 'DECKS_REMOVE_DATA';
export const DECKS_UPDATE_FILTER = 'DECKS_UPDATE_FILTER';

export const DECK_SET_TESTING = 'DECK_SET_TESTING';
export const DECK_EMPTY_RESULTS = 'DECK_EMPTY_RESULTS';
export const DECK_QUIZ_RESET = 'DECK_QUIZ_RESET';
export const DECK_QUIZ_SET_ACTIVE_SLIDE = 'DECK_QUIZ_SET_ACTIVE_SLIDE';
export const DECK_QUIZ_SET_QUESTION_CORRECT = 'DECK_QUIZ_SET_QUESTION_CORRECT';
export const DECK_QUIZ_SET_FINISHED = 'DECK_QUIZ_SET_FINISHED';
export const DECK_SET_QUIZ_DEFAULT_SWIPE_CORRECT = 'DECK_SET_QUIZ_DEFAULT_SWIPE_CORRECT';
export const DECK_SET_CAROUSEL_INITIALIZED = 'DECK_SET_CAROUSEL_INITIALIZED';

export const DECK_SET_EDIT_OVERLAY_VISIBLE = 'DECK_SET_EDIT_OVERLAY_VISIBLE';
export const DECK_SET_IS_EDITING_CARD = 'DECK_SET_IS_EDITING_CARD';
export const DECK_EDIT_CARD_VALUE = 'DECK_EDIT_CARD_VALUE';
export const DECK_CLEAR_CARD_EDIT_VALUES = 'DECK_CLEAR_CARD_EDIT_VALUES';

export const CREATE_SET_TITLE = 'CREATE_SET_TITLE';
export const CREATE_ADD_QUESTION = 'CREATE_ADD_QUESTION';
export const CREATE_SET_CREATE_OVERLAY_VISIBLE = 'CREATE_SET_CREATE_OVERLAY_VISIBLE';
export const CREATE_SET_IS_EDITING_CARD = 'CREATE_SET_IS_EDITING_CARD';
export const CREATE_EDIT_CARD_VALUE = 'CREATE_EDIT_CARD_VALUE';
export const CREATE_CLEAR_CARD_EDIT_VALUES = 'CREATE_CLEAR_CARD_EDIT_VALUES';
export const CREATE_DECK_RESET = 'CREATE_DECK_RESET';
